/**
 * Auto-generated contract ABIs
 * 
 * Generated by: npm run compile
 * Do not edit manually!
 */

import VotingABI from "./Voting.json";
import GroupManagerABI from "./GroupManager.json";

export const abis = {
  Voting: VotingABI,
  GroupManager: GroupManagerABI,
} as const;

export { VotingABI, GroupManagerABI };
